language: node_js
node_js: 
  - 8
cache:
 directories:
  - node_modules
script:
  - npm run-script build 
  - npm test -- --coverage && cat ./coverage/lcov.info | coveralls
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: master  


